spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/profile-service?authSource=admin

server:
  port: 9002
  servlet:
    context-path: /profile/