spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/profile-service?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/web-app

server:
  port: 9002
  servlet:
    context-path: /profile/

idp:
  url: http://localhost:8180
  client-id: web_app
  client-secret: AaMGYgpOLUdyQwIrCDkN9isidxvGYYg0


logging:
  level:
    org.springframework.security: debug
    org.springframework.security.web.access.ExceptionTranslationFilter: TRACE
    org.springframework.security.web.access.AccessDeniedHandlerImpl: TRACE
