spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/profile-service?authSource=admin

server:
  port: 9002
  servlet:
    context-path: /profile/

idp:
  url: http://localhost:8180
  client-id: web_app
  client-secret: AaMGYgpOLUdyQwIrCDkN9isidxvGYYg0
